[dependencies]
pyo3 = {version = "0.29.0", features = ["extension-module", "abi3-py310"]}
unicode-linebreak = "0.1.5"
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"

[lib]
crate-type = ["cdylib"]
name = "unicode_segmentation_rs"

[package]
authors = ["Michal Čihař <michal@weblate.org>"]
description = "Unicode segmentation and width for Python using Rust"
edition = "2024"
license = "Apache-2.0"
name = "unicode-segmentation-rs"
readme = "README.md"
repository = "https://github.com/WeblateOrg/unicode-segmentation-rs"
version = "0.3.0"
